# Generated by Django 6.0.1 on 2026-01-28 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/pickup/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/return/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('returned', 'Returned'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.tool'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tool_images/'),
        ),
    ]
