# Generated by Django 6.0.1 on 2026-02-08 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_timestamp_booking_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(max_length=200),
        ),
    ]
